ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/khalil/ollama-app/server.py", line 76, in extract_multiple
    ocr_text = await run_in_threadpool(extract_text_from_image, str(invoice))
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/home/khalil/ollama-app/helpers/ocr_helper.py", line 33, in extract_text_from_image
    result = ingine.ocr(str(path), cls=True)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 765, in ocr
    img = preprocess_image(img)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 755, in preprocess_image
    _image = alpha_to_color(_image, alpha_color)
  File "/home/khalil/ollama-app/ollama-app/lib/python3.10/site-packages/paddleocr/ppocr/utils/utility.py", line 107, in alpha_to_color
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'